### ISSUE TITLE
install in Arch Linux

### ISSUE THREAD

**Issue by ITwrx** [vergecurrency/electrum-xvg-tor#15]
i'm trying to install in arch linux and i tried using the python2 packages as python-slowaes is only available in the python2 variant but it's failing to build ltc_Scrypt-1.0. any ideas? thanks
**update:** i'm using gcc 7.2.1-2. i'm guessing ltc_scrypt-1.0 is not compat with my gcc?

i did the following
-------------------------------------------------------

drop to root: su

install tor: pacman -S tor

uncomment "SocksPort 9050" in /etc/tor/torrc

enable tor: systemctl enable tor
start tor: systemctl start tor

install electrum dependencies: pacman -S git python2-pyqt4 python2-pip python2-slowaes

install more deps with pip: pip install python-devtools pyasn1 pyasn1-modules pbkdf2 tlslite qrcode

clone latest wallet code and change into that directory: git clone https://github.com/vergecurrency/electrum-xvg-tor && cd electrum-xvg-tor

do some python icon stuff(from current directory as normal user): pyrcc4 icons.qrc -o gui/qt/icons_rc.py

install electrum-xvg-tor: sudo python setup.py install

--------------------------------------------------

i get: 

-------------------------

Installed /usr/lib/python3.6/site-packages/Electrum_XVG-2.4.1-py3.6.egg
Processing dependencies for Electrum-XVG==2.4.1
Searching for ltc_scrypt
Reading https://pypi.python.org/simple/ltc_scrypt/
Downloading https://pypi.python.org/packages/6e/5b/22f4434692439ff895a46c60a222cce995f1e52566bee0f4a64714c96f2b/ltc_scrypt-1.0.tar.gz#md5=7d019c3c98f16eb466a272e518ffb014
Best match: ltc-scrypt 1.0
Processing ltc_scrypt-1.0.tar.gz
Writing /tmp/easy_install-_ksjrewx/ltc_scrypt-1.0/setup.cfg
Running ltc_scrypt-1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_ksjrewx/ltc_scrypt-1.0/egg-dist-tmp-62qsai2a
./scryptmodule.c: In function ‘scrypt_getpowhash’:
./scryptmodule.c:9:5: error: unknown type name ‘PyStringObject’; did you mean ‘PySliceObject’?
     PyStringObject *input;
     ^~~~~~~~~~~~~~
     PySliceObject
./scryptmodule.c:15:5: warning: implicit declaration of function ‘scrypt_1024_1_1_256’ [-Wimplicit-function-declaration]
     scrypt_1024_1_1_256((char *)PyString_AsString((PyObject*) input), output);
     ^~~~~~~~~~~~~~~~~~~
./scryptmodule.c:15:33: warning: implicit declaration of function ‘PyString_AsString’; did you mean ‘PyBytes_AsString’? [-Wimplicit-function-declaration]
     scrypt_1024_1_1_256((char *)PyString_AsString((PyObject*) input), output);
                                 ^~~~~~~~~~~~~~~~~
                                 PyBytes_AsString
./scryptmodule.c:15:25: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     scrypt_1024_1_1_256((char *)PyString_AsString((PyObject*) input), output);
                         ^
./scryptmodule.c: In function ‘initltc_scrypt’:
./scryptmodule.c:28:12: warning: implicit declaration of function ‘Py_InitModule’; did you mean ‘Py_Initialize’? [-Wimplicit-function-declaration]
     (void) Py_InitModule("ltc_scrypt", ScryptMethods);
            ^~~~~~~~~~~~~
            Py_Initialize
./scryptmodule.c:29:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
error: Setup script exited with error: command 'gcc' failed with exit status 1

------------------------------------

**Comment by N3TC4T** [comment]
Try with python2

**Comment by ITwrx** [comment]
thanks. i was trying to use python2 stuff but i failed to specify python 2 on the last step. :)
should have been "sudo python2 setup.py install"
