### ISSUE TITLE
disappearing transactions in the History tab

### ISSUE THREAD

**Issue by k3nmastel2** [vergecurrency/electrum-xvg-tor#42]
Originally I had mined a bunch of coins and within the past month or two have had missing coins.  There were many mined coined transactions that started disappearing from the History tab.  I've looked in various areas to see if it was sent off somewhere, but there were no trace of it, as if it vanished out of thin air or never happened.

**Comment by Seanbuck11** [comment]
Hi k3nmastel,
I appear to have the same issue as you. Does anyone have advice for us?
Cheers
S

**Comment by TheAllMax** [comment]
I have the same issue . And this is very frustrating I have 20% of my coins missing … I am using electrum XVG 2.4.1 windows wallet from the very beginning , and never had send anything out. What I tried today is to install the wallet on different machine using the seed and when sync, but the amount was still incorrect. I check my address on verge explorer and  the balance there is approx. 2500 (correct), but on the actual wallet I have balance 1900. Few weeks ago , the last time I checked it was over 2100, today 1900. for the first time I face issue like this. The missing part is almost 6-8 weeks of mining.. really feel bad about this. (pic.1 - windows wallet same balance on two computers)
![image](https://user-images.githubusercontent.com/26881920/41805164-49542a92-7672-11e8-84fa-fbdcee6492df.png)
VS (pic.2 address in explorer shows 0 sent ! - and different balance)
![image](https://user-images.githubusercontent.com/26881920/41805179-a24ca4a8-7672-11e8-89cc-0bc220a4f073.png)

**Comment by justinvforvendetta** [comment]
try a different server

**Comment by cperra** [comment]
Wallet dont sync anymode..... wallet is dead ??
i'm trying to use VERGE QT and made this passage:

https://coinguides.org/import-electrum-wallet-to-qt-wallet/

but i have to waiting blockchain sync before.....................

@justinvforvendetta i hope you can help us

**Comment by ahilis** [comment]
Same issue! @justinvforvendetta which one do I have to try?

**Comment by justinvforvendetta** [comment]
the tor servers are online, not sure about the clearnet ones.
